name: lab3-fmri

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - tables
  - joblib
  - ipykernel
  - jupyterlab
  - pip
  - pip:
      - nltk
      - gensim

