name: stat214
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - graphviz
  - python-graphviz
  - jupyterlab
  - nbconvert
  - ipykernel