data:
  patch_size: 9
dataloader_train:
  batch_size: 4096 #8192
  num_workers: 4
  shuffle: True
dataloader_val:
  batch_size: 4096 #8192
  num_workers: 4
  shuffle: False
autoencoder:
  n_input_channels: 8
  embedding_size: 8
optimizer:
  lr: 0.001
trainer:
  max_epochs: 50 #200  ## smaller max_epochs
  log_every_n_steps: 50
early_stopping:  ## add early stopping to aviod overfitting
  monitor: "val_loss"  
  patience: 10        
  mode: "min"
  min_delta: 0.001
  verbose: True       
checkpoint:
  save_top_k: 3
  monitor: 'val_loss'
  mode: 'min'
  filename: 'exp-{epoch:03d}-{val_loss:.4f}'
  dirpath: 'checkpoints/exp_0316'
wandb:
  project: 'lab2-autoencoder'
  name: 'default'
    # you should change "default" to something else
    # for your experiments
